# ソースからビルド + マイグレーション用
# package.json, prisma/ がプロジェクトルートにある構成
steps:
  - name: node:20
    id: install
    entrypoint: bash
    args:
      - '-lc'
      - |
        set -e
        yarn install

  - name: node:20
    id: build
    entrypoint: bash
    args:
      - '-lc'
      - |
        set -e
        yarn build
    waitFor: ['install']

  - name: node:20
    id: migration
    env:
      - NODE_ENV=$_NODE_ENV
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_DATABASE=$_DB_DATABASE
      - DB_USERNAME=$_DB_USERNAME
      - DB_PASSWORD=$_DB_PASSWORD
    entrypoint: bash
    args:
      - '-lc'
      - |
        set -e
        echo "Downloading Cloud SQL Auth Proxy..."
        curl -sSLo cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.11.4/cloud-sql-proxy.linux.amd64
        chmod +x cloud-sql-proxy

        echo "Starting Cloud SQL Auth Proxy..."
        ./cloud-sql-proxy "${_INSTANCE_CONNECTION_NAME}" --port=3306 &
        PROXY_PID=$$!

        sleep 3

        echo "Building DATABASE_URL with URL-encoded password..."
        export DATABASE_URL=$$(node -e "
          const user = process.env.DB_USERNAME;
          const pass = encodeURIComponent(process.env.DB_PASSWORD || '');
          const host = process.env.DB_HOST;
          const port = process.env.DB_PORT;
          const db = process.env.DB_DATABASE;
          console.log('mysql://' + user + ':' + pass + '@' + host + ':' + port + '/' + db);
        ")

        echo "Running migration..."
        yarn migration:run

        echo "Stopping Cloud SQL Auth Proxy..."
        kill $$PROXY_PID
        wait $$PROXY_PID || true

        echo "Migration finished successfully."
    waitFor: ['build']

options:
  logging: CLOUD_LOGGING_ONLY
