#!/bin/bash
echo "========================================="
echo "Cloud Build 手動実行スクリプト"
echo "========================================="
echo ""
echo "このスクリプトを実行すると、Cloud Buildのビルドが開始されます。"
echo "gcloud CLIが必要です。"
echo ""
echo "実行前に以下を確認してください："
echo "1. Google Cloud プロジェクトが設定されている"
echo "2. Cloud Build APIが有効になっている"
echo "3. Cloud Run Admin APIが有効になっている"
echo ""
echo "ビルドを開始しますか？ (y/n)"
